### ISSUE TITLE
On Azure, on production system, carbon estimation is done only for current month

### ISSUE THREAD

**Issue by PadmarajBhat** [cloud-carbon-footprint/cloud-carbon-footprint#1275] opened 2023-12-01 04:53 UTC
### Preflight Checklist

- [ x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  Windows 10 (1803) 
- **Browser:**
  Microsoft Edge

### Expected Behavior

An year long data has to be fetched and carbon emission has to be computed.

### Actual Behavior

only current month billing data is fetched and current month carbon estimation is shown in the chart

### To Reproduce

Azure account with multiple subscription.

When only one subscription was configured even then only one month carbon emission was shown.

There were frequent Azure Consumption warnings as indicated in the log below
[CCF CMD Logs.txt](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/files/13520777/CCF.CMD.Logs.txt)

### Screenshots

logs attached
### Additional Information

we made code changes to print the Azure response at
File: ConsumptionManagement.ts
Function: pageThroughUsageRows
Line #325

Code:
```
   } catch (error) {
      throw error
    }
#########################################################################
    this.consumptionManagementLogger.debug("usageRowDetails: Array Size : "+ usageRowDetails.length
    +" subscriptionName : "+usageRowDetails[0]?.subscriptionName
    +" FirstArrayElementDate :"+usageRowDetails[0]?.date
    + " LastArrayElementDate :"+usageRowDetails[usageRowDetails.length-1]?.date);

#########################################################################
    return usageRowDetails
```
What we saw in logs is that for each old data requested, Azure seems to sending only current month data irrespective of "REACT_APP_GROUP_BY" or "AZURE_CONSUMPTION_CHUNKS_DAYS" or "REACT_APP_DATE_RANGE_VALUE" combinational values.

[output_log_dec_2.log](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/files/13682269/output_log_dec_2.log)

Attached log indicates 

at log line #49 : usage details was request between 2023-09-11T00:00:00.000Z to 2023-09-16T23:59:59.999Z
at line#51: instead of September , December data was returned.

There are multiple examples of the same in the log.

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment] 2024-01-06 05:59
Hi @PadmarajBhat sorry for the late follow up on this and thanks for opening this issue with such detailed information! 

Based on your findings, it does give the initial impression that the Azure Consumption-Usage API is not returning the correct response. As a heads up, we are in the middle of migrating to use the new Cost Details API as noted in #1204 and #1279 for enterprise customers. However, the deprecation date for the current API is still a little time away and shouldn't be exhibiting strange behavior yet.

I'm having a bit trouble replicating on this on my side, so I'm wondering if this is a breaking change in a more recent version of the API. Would you mind sharing the current version of the @azure/consumption-arm package that your CCF instance is using as well as the type of Azure account you're querying (pay-as-you-go, EA, MCA, etc)? 

FYI - You can find the package version by running the `yarn why @azure/arm-consumption` command in the root directory of your project.

**Comment by PadmarajBhat** [comment] 2024-01-08 08:04
I am not able to recreate in my Dev env. I am able to get the past year day wise data on my local.

My env:
Code : latest pull
Azure Account type : EA
package version:
 @cloud-carbon-footprint/azure@workspace:packages/azure
│  └─ @azure/arm-consumption@npm:9.2.0 (via npm:^9.2.0)
│
└─ @cloud-carbon-footprint/cli@workspace:packages/cli
   └─ @azure/arm-consumption@npm:9.2.0 (via npm:^9.2.0)

More or less client also has same set up. However, we dont see old data in production/client env.

**Comment by 4upz** [comment] 2024-01-08 18:42
@PadmarajBhat Interesting, are you able to verify the versions that the production app is using? I think from this point, it would be helpful to isolate any differences that your local env has from your production environments. So within that same line of thinking, are there any other differences in configuration that the prod version of your app is using? Are they both pulling from the same account?

If you mind providing details of how you're deploying your app to production (i.e. virtual machine, serverless option, containerized app, etc) that would be helpful as well.

**Comment by 4upz** [comment] 2024-01-09 16:29
I was finally able to replicate this by making a request for Azure data using a date range that our Azure account does not have usage/consumption within. 

Using the same logging to print the API response it seems that for certain Azure subscriptions, the Consumption API defaults to returning the last ~7 days of data. Other subscriptions return empty results.  However, while this was still happening behind the scenes, we have logic in [ConsumptionManagement.ts#L116-120](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/b1679ec5a14ec71e4949706f46e6e452eb1cee18/packages/azure/src/lib/ConsumptionManagement.ts#L116-L120) that filters out any results that are not within the date range. As a result, I was still getting an empty array (expected behavior) for the API response when getting results. However, if these are still being returned as an API response despite not being within the queried date range then that's certainly a bug.

We plan on still investigating why Azure's API responds this way just to ensure that we're still handling this situation gracefully. My guess is that the different behavior amongst subscriptions are due to some subscriptions using Legacy billing details and other using Modern details -- which both have different filtering behaviors/endpoints on Azure's side.

@PadmarajBhat I can only imagine you are seeing different behavior locally vs your client/prod environment if the two environments are using separate accounts with different usage availability. The above questions in my previous post would be helpful to know, but can you confirm whether you are seeing an API response that includes data outside of the requested date range when this occurs? An example of this would be as mentioned in your original post -> Requesting 9-11-2023 to 9-16-23 data from the API but seeing a JSON response that includes December data.

**Update/Edit**: I can confirm that only Modern Usage Details return this type of response. So this must be a difference with Azure's Modern Consumption Details API/Filtering

**Comment by PadmarajBhat** [comment] 2024-01-10 07:51
Client account type :  EA
Production yarn output:
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/2c86de8a-adb5-42fe-a9a2-7407f422039d)

Client has a dedicated windows machine (virtual machine) for CCF 
![image](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/29166528/e3d955f2-0779-44f8-bd97-d104fcdcc49f)

We did git pull
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint.git today and same issue reproduced.

**Comment by 4upz** [comment] 2024-01-10 16:09
@PadmarajBhat Awesome, thanks for clarifying it's a virtual machine. As for the rest of the details, the hardware or operating system shouldn't be affecting the app. When referring to environment differences, I was referring to the configuration of CCF (connected accounts, env variables, etc) between your local machine and the client's. Sorry, allow me to rephrase my follow-up questions:

Is your client's CCF application pulling data from the same Azure account as your local machine? Or are they using different accounts? 

As a follow-up, if they are using different accounts, are you sure that your client's Azure account has usage for the date range that is requested when seeing this issue? And for that date range requested, are you seeing the wrong dates included in the API response? Or are you getting an empty array of estimates as an API response and only seeing the dates appear as a raw response from Azure's API when logging?

**Comment by PadmarajBhat** [comment] 2024-01-11 05:49
1. Yes, the 2 envs are different.  In my local setup I fetch my dev emissions through CCF. In production, it is clients account data. I didnt try the client account at local as it violates the data pricy agreement. 

2. Client has at least 1 and half years of data as they migrated around 2 years back to Azure. Apart from that, when we ran CCF yesterday, we could get only Jan data (day wise) but NOT  Dec and Nov. Note that wee could pull Nov and Dec day wise report in respective months. Now, its only through our old json (backup file), we could see Nov, Dec and Jan in a chart.

3. If we start afresh then we get only Jan charts and json file will be empty for the field "serviceEstimates" for older dates. However, at my local on my azure account, I could get year long data each time I start afresh.

4. We get the full json but with current month data to whatever old date request it was for.  Log file has only dates for data privacy concerns. 

5. We have log statements immediately before to the request and immediately after the response. So input dates and output dates are not corrupt/incorrect.

**Comment by 4upz** [comment] 2024-01-11 22:16
@PadmarajBhat Thanks for the detailed response. Based on your description, with the only variable between the two deployments being the Azure accounts used, this sounds like an issue with how the Azure API is handling responses for the different accounts.

I'm a bit skeptical that both accounts used are Enterprise Agreements. The behavior for your client's account sounds like behavior that has come up with a Microsoft Customer Agreement (MCA) account -- think of it as a modern EA subscription. Feel free to confirm and correct me if I'm wrong on this.

 We've identified behavior for these account types in #1113. This is primarily due to the different billing systems that the account types. Unfortunately, the Azure SDK that we use does not support start and end date filtering for MCA accounts, which is why you're only seeing data for the current billing cycle returned (default behavior for modern usage details without date filtering passed).

As a workaround, you could modify your CCF instance directly to make a direct fetch for usage data to the Usage Details API via URL with the appropriate parameters. I'd recommend checking out this [open issue on the matter](https://github.com/Azure/azure-rest-api-specs/issues/11849) for more details. Just be aware of any differing pagination logic from our current implementation that you may need to implement.

 The effort to add support for this with the current API would outweigh its benefits since we are already migrating to the Cost Details API where modern/legacy schemas are unified and this issue is fixed. As a result, I'll go ahead and close this issue. Feel free to also check out #1175 and follow #1222 for updates on this, and don't hesitate to let us know if you have more questions or concerns!

**Closed as completed by 4upz** 2024-01-11 22:16 UTC
