### ISSUE TITLE
Docker deployment release-2023-11-13 - Nginx 403 directory index of "/var/www/" is forbidden

### ISSUE THREAD

**Issue by jhauray** [cloud-carbon-footprint/cloud-carbon-footprint#1272] opened 2023-11-27 16:43 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  -  Azure App Service Linux Powered by Debian 11
- **Browser:**
  -  Chrome 119.0.6045.160

### Expected Behavior

Browsing https://xxxxxxxxxx.azurewebsites.net/ should return answer status 200 and Cloud Carbon Footprint Dashboard.

### Actual Behavior

When browsing https://xxxxxxxxxx.azurewebsites.net/, a http 403 error is returned by nginx.

### To Reproduce

 - Create an Azure Web App, linux multi-container type.
 -  Copying docker-compose https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/docker-compose.yml
 -  Setting port mapping to follow Azure requirements :
```yaml
     ports:
      - '8000:80'
```
 - Disabling AWS and GCP parameters in docker compose.
 - updating client volumes as below : 
```yaml
    volumes:
      - ${WEBAPP_STORAGE_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WEBAPP_STORAGE_HOME}/LogFiles/nginx/:/var/log/nginx/
```
- In Web App, create a folder `~/nginx` and copy  https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/docker/nginx.conf in this folder.
- Deploy docker-compose
- browse https://xxxxxxxxxx.azurewebsites.net/

### Screenshots

![Capture pcf nginx error](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/assets/42616019/ae607b3a-9759-410b-9950-e0d1e93c2f13)

### Additional Information

Nginx error logs contains following error :
2023/11/27 16:02:22 [error] 30#30: *2 directory index of "/var/www/" is forbidden, client: xxxx.xxxxx.xxx.xx server: , request: "GET / HTTP/1.1", host: "xxxxxxxxxx.azurewebsites.net"
2023/11/27 16:02:27 [error] 30#30: *2 directory index of "/var/www/" is forbidden, client: xxxx.xxxxx.xxx.xx, server: , request: "GET / HTTP/1.1", host: "xxxxxxxxxx.azurewebsites.net", referrer: "https://xxxxxxxxxx.scm.azurewebsites.net/"

Docker seems to not have rights to read files.

log files have been created with user id 65534 (nobody). Azure App Service seems to run docker with non-root user.

© 2021 Thoughtworks, Inc.

**Comment by aadrm** [comment] 2023-12-01 13:55
I believe that the issue is within the latest docker image and is not a compatibility issue with Azure App Service. Nginx is expecting an `index.html` inside `/var/www/`. However, if you have a look at the contents of the container's `/var/www/`. You'll find the following:

```
App.d.ts
App.js
App.js.map
Config.d.ts
Config.js
Config.js.map
ConfigLoader.d.ts
ConfigLoader.js
ConfigLoader.js.map
Root.d.ts
Root.js
Root.js.map
Types.d.ts
Types.js
Types.js.map
asset-manifest.json
common
favicon.ico
index.d.ts
index.html
index.js
index.js.map
layout
lib.d.ts
lib.js
lib.js.map
package.json
pages
robots.txt
setupTests.d.ts
setupTests.js
setupTests.js.map
static
utils
```
Instead of the expected:
```
asset-manifest.json
favicon.ico
index.html
robots.txt
static
```
The root cause I believe lays in commit  #[96828d7](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/96828d71a2edfb8955c214ea1f337eff9e0e2faa). Where the contents of `./dist` instead of `./build` are copied into `/var/www/`.  The title of the commit mentions that it fixes a "build issue with client Dockerfile", so even though the change allows a successful build, it seems to lead to the Nginx error in the deployed image.

I got my container to work by navigating into /packages/client, then running `yarn build:app`, and then replacing the contents of the container's `/var/www` with the contents of the newly generated `build` directory.

**Comment by 4upz** [comment] 2023-12-04 21:37
Hi @jhauray sorry that you're running into this issue. As @aadrm mentioned, this is indeed not an Azure App Service issue and an issue with the latest client image. The build directory was incorrect thus causing the nginx error.

We are testing this and should have a fix released soon. However, if you need to be unblocked before then, you can pull the docker image of the prior release via `docker pull cloudcarbonfootprint/client:release-2023-10-17`,

Thanks for drawing attention for this and another thanks to @aadrm for looking into this

**Comment by jhauray** [comment] 2023-12-05 07:36
Hello @aadrm and @4upz,

Thank you for your answers.

I will test with previous version to confirm root cause.

If it is confirm, I will update issue title.

**Comment by jhauray** [comment] 2023-12-05 12:35
Hello @aadrm and @4upz,

I confirm with previous docker version, web app (client) is ok on Azure App Service hosting.

**Comment by 4upz** [comment] 2023-12-06 21:10
Thanks for confirming @jhauray 

We released a new version of the client image with the necessary fix. You should now be able to pull a working image using `docker pull cloudcarbonfootprint/client:latest`. Closing this but happy to re-open if the issue persists

**Closed as completed by 4upz** 2023-12-06 21:10 UTC
