### ISSUE TITLE
Client API Footprint requests are not correctly concatenated

### ISSUE THREAD

**Issue by mgriffin-scottlogic** [cloud-carbon-footprint/cloud-carbon-footprint#1193] opened 2023-08-02 09:29 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (22H2)
- **Browser:**
  - Chrome

### Expected Behavior

When data is requested from the /footprint endpoint multiple times using the limit and skip query parameters, the resulting graphs should combine results where dates are split across requests.

### Actual Behavior

Graphs only display the total of results from the first request where a date was split.

### To Reproduce

Don't have a publicly shareable dataset but this can be reproduced in a test by modifying https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/client/src/utils/hooks/FootprintServiceHook.test.ts to include the following expectations in the last test:
```
      expect(result.current.data[0].serviceEstimates.length).toEqual(2)
      expect(result.current.data[0].serviceEstimates[1]).toEqual(
        mockEstimateTwo.serviceEstimates[0]
      )
```

### Screenshots

N/A

### Additional Information

Planning to submit PR with fix

**Comment by 4upz** [comment] 2023-08-02 18:44
@mgriffin-scottlogic Thanks for opening this issue and catching this! I can confirm that I'm seeing similar behavior on my side, and appreciate you also being willing to submit a PR for this

This seems to be stemming from an issue in the `FootprintServiceHook.ts` file's `concatenateResults` function where the wrong value is being fetched to[ find the index of the element ](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/fa933d453429f30e20f8d39b6f1b8a5f6c52563c/packages/client/src/utils/hooks/FootprintServiceHook.ts#L126)with the matching timestamp. At a glance, a simple fix of changing the used array function from `find` to `findIndex` should fix the issue. Nice suggestion on the extra test assertion!  

Feel free to let us know if you need any support while creating the PR, and I'll be happy to review it once it's ready.

**Comment by mgriffin-scottlogic** [comment] 2023-08-02 20:35
Thanks for the reply, yes my fix was just to change find to findIndex. I was attempting to commit it to a fork earlier but hadn't managed to get the pre-commit tests to pass cleanly. Initially had difficulty with crlf line endings on Windows and then there was a failing test related to CSV files in the CLI package, which I hadn't investigated yet.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 4upz** [comment] 2023-08-02 23:10
@mgriffin-scottlogic Sorry you're running into that issue. Perhaps it's a difference in versions between the fork? If you're unable to get around it and are confident you didn't affect those tests, you're welcome to use `--no-verify` flag on your commit to skip the pre-commit so that it doesn't block the PR process.

We have a workflow that will rerun all tests against a branch of the merged changes once the PR is open. So we'll be able to verify them during the review

**Closed as completed** 2023-08-07 13:38 UTC
