### ISSUE TITLE
Sorting by carbon savings when using metric tons or kg should result in the same order

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#450] opened 2021-09-02 18:41 UTC
**Context**
In order to give a better picture of which recommendations will lead to the greatest carbon savings, we added in a feature to show it in terms of kg, which is a better fit when dealing with smaller values.
 **Description of Issue**

**Comment by akhil-ghatiki** [comment] 2021-09-10 12:03
Tried to reproduce this issue with the mock data. Unable to reproduce this. 
@ericksod Can you please give inputs in how to reproduce this ?

**Comment by ericksod** [comment] 2021-09-14 14:27
hi @akhil-ghatiki! Thanks for looking into this.
I think perhaps the mock data doesn't have the numbers needed to reproduce the issue. I will put some more info in the ticket with some sample numbers that may help with reproducing.

**Comment by akhil-ghatiki** [comment] 2021-09-30 16:28
I see this sorting order is justified when we are toggling from metric tons to kilograms.
since the values are rounded of to the nearest decimal, a set different values will be rounded off to the same value, hence the further sorting depends of other columns.
or ex: 
case 1 : 4.268 , 4.369, 4.478 etc will all get rounded to 0.004 only
case 2 : any value greater than 4.5 will get rounded to 0.05

in case 1 the sorting will be decided by Account name column
hence we are see difference in sort when toggling

I am discussing this with @ccasher and we are in sync. Looking into cases where we can improve the rounding off the values

**Comment by akhil-ghatiki** [comment] 2021-10-07 15:16
I have updated the PR with some new changes. Changed the place where we handle the precision and opted for a precision of 10 digits after decimal. From my observation, higher the precision, lower is the probability that sorting order will change when toggled. 
cc: @ccasher @ericksod

**Comment by akhil-ghatiki** [comment] 2021-10-15 16:05
made some changes to the PR. Let me know your opinion on this.

**Comment by ccasher** [comment] 2021-10-29 14:39
Thanks for contributing Akhil! This was succesfully merged!

**Closed as completed** 2021-11-03 23:24 UTC
Labels: bug, good first issue, hacktoberfest
