### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#1011] opened 2023-01-13 14:48 UTC
### Preflight Checklist

- [ x ] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 11 22621.1105
- **Browser:**
  - None

### Expected Behavior

When i launch cli, I expect to have results

### Actual Behavior

`FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

### To Reproduce

- npx installation of CCF
- configured for AWS (aws cli)
- `yarn start` is OK (can browse data in web interface)
- `yarn start-cli --startDate '2022-07-31' --endDate '2022-08-31'` (or whatever date, even 1 day) fails

```
2023-01-13T14:35:19.491Z [Cache] info: Using local cache file...
(node:26696) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\code\cloud-footprint\ccf-npx\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:26696) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\code\cloud-footprint\ccf-npx\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(node:26696) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\code\cloud-footprint\ccf-npx\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(node:26696) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\code\cloud-footprint\ccf-npx\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(node:26696) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\code\cloud-footprint\ccf-npx\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(node:26696) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\code\cloud-footprint\ccf-npx\node_modules\@cloud-carbon-footprint\core\dist\package.json' of 'dist/index.js'. Please either fix that or report it to the module author

<--- Last few GCs --->

[26696:0000015B3D593900]   228515 ms: Mark-Compact 16146.5 (16424.9) -> 16135.8 (16429.4) MB, 10288.0 / 0.0 ms  (average mu = 0.246, current mu = 0.001) allocation failure; scavenge might not succeed
[26696:0000015B3D593900]   242501 ms: Mark-Compact 16151.7 (16429.4) -> 16140.9 (16434.6) MB, 13959.5 / 0.0 ms  (average mu = 0.122, current mu = 0.002) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7964EACCF node_api_throw_syntax_error+175359
 2: 00007FF79646FDA6 v8::internal::wasm::WasmCode::safepoint_table_offset+65478
 3: 00007FF796471163 v8::internal::wasm::WasmCode::safepoint_table_offset+70531
 4: 00007FF796F9C481 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF796F870D6 v8::internal::V8::FatalProcessOutOfMemory+662
 6: 00007FF796DED7F0 v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+144
 7: 00007FF796DEA80D v8::internal::Heap::CollectGarbage+4749
 8: 00007FF796E00436 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2150
 9: 00007FF796E00D6F v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+95
10: 00007FF796E0FF90 v8::internal::Factory::NewFillerObject+448
11: 00007FF796AC5A55 v8::internal::Runtime::SetObjectProperty+20997
12: 00007FF797045BD1 v8::internal::SetupIsolateDelegate::SetupHeap+606705
13: 00007FF7176B6D01
```
Tried to go to 32768 MB ( `$env:NODE_OPTIONS="--max-old-space-size=32768" ; yarn start-cli --startDate '2022-07-31' --endDate '2022-08-31'` ), same behavior

**Comment by 4upz** [comment] 2023-01-19 14:34
Hi @jeromemoly thanks for submitting this issue! It seems that this is happening on our end as well. We're adding this to our project board and will work on releasing a fix as soon as possible

**Comment by 4upz** [comment] 2023-01-19 22:53
Issue was caused by required `groupBy` param not being passed to the estimation request in the CLI. Commit https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/d388be0f34c0002d04edbd885b4714c36f181fab should fix it by adding the missing param, and properly assigning a default value when not provided by the user.  Also added more tests for parameter validations.

**Comment by 4upz** [comment] 2023-01-20 22:10
Fix has been reviewed and included in the latest Create-App release. Going to close this as complete, but @jeromemoly thanks again for reporting this issue! Feel free to give it another spin by creating a new app using the latest npx package or incorporating the changes to your existing one by following this [commit](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/4eee1afeb8d870a6976342f0c0cfe82b75c965b2), and let us know if you still encounter the issue.

**Closed as completed by 4upz** 2023-01-20 22:10 UTC
