### ISSUE TITLE
Loading cloud data. This may take a while...

### ISSUE THREAD

**Issue by 365fed** [cloud-carbon-footprint/cloud-carbon-footprint#1169] opened 2023-06-19 15:42 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://www.cloudcarbonfootprint.org/docs/getting-started) for this project
- [x] I have modified the .env file
- [x] I have ran the project successfully ( $ yarn start )

### Issue Details

- **First:**
  - Request API : /api/footprint?start=2023-03-01&end=2023-06-01&ignoreCache=false&groupBy=day&limit=50000&skip=0
- **Second:**
  - The page is consistently in a loading state with the message "Loading cloud data. This may take a while..." and it takes several tens of seconds or even more to complete. How can the page performance be improved or the query speed be optimized?

### Expected Behavior

Expect the page to request data quickly and reduce loading time

### Actual Behavior

The page loading time is too long, and sometimes there is no response at all

© 2021 Thoughtworks, Inc.

**Do you have any good solutions? I am eagerly looking forward to your reply. Thank you!**

**Comment by 4upz** [comment] 2023-06-20 18:29
Hi @365fed, unfortunately, this is expected behavior. Since we gather usage data by fetching billing data from each configured cloud provider, fetching that data can take some time depending on your usage size and which cloud provider is being queried. Initial requests can take anywhere from tens of seconds to a few minutes depending on your account size, grouping method, and date range.

This is why we have implemented [Data Persistence and Caching](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching) to persist estimates and speed up subsequent requests. If you are dealing with large usage or accounts, we'd recommend configuring the more robust MongoDB method for saving your usage data.

We do have some workarounds for specific cloud providers that you can use to assist with performance. We recommend checking out the [Performance Considerations](https://www.cloudcarbonfootprint.org/docs/performance-considerations) section of our documentation for more information. 

Hope that helps! Closing since there aren't any actionable steps on our side, but happy to still take additional questions, suggestions, or concerns.

**Closed as completed** 2023-06-20 18:30 UTC

**Comment by 365fed** [comment] 2023-06-21 02:48
Hi@4upz, thank you for your feedback and I'm glad that i learned a lot! As for your question, does CCF have any automated triggered scheduled tasks? For example, running a job once a day to pull the latest data and cache it. How do you solve the problem of data synchronization? I found a background job for cli can  manually run scheduled task,but any automated triggered scheduled tasks? thx!

**Comment by 4upz** [comment] 2023-06-21 15:01
@365fed Glad it was helpful! At this moment, CCF doesn't have any out of the box solutions for scheduling automated tasks. Due to the various environments and infrastructure that our users have, it may be difficult to come up with a one-size-fits-all solution for this. However, we're always open to accepting PRs with templates/recommendations for what worked for others.

We do, however, plan on soon creating a high-level guide for how automated tasks to keep your emissions data updated can be achieved. You are correct in that we've included the [Seed Cache File](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching/#seeding-cache-file) CLI script to help make this easier to setup. Fortunately, the solution isn't too difficult if you're comfortable with writing a few lines of code. What we've found is that most people setup a cloud function (i.e. AWS lambda) that is triggered to run daily, and either makes an API request or kicks off a CLI task to fetch data for the current date.

**Comment by 365fed** [comment] 2023-07-19 12:55
@4upz I have configured MongoDB cache according to the official documentation and it's successful. However, when using MongoDB cache, I found that it still takes about 2 minutes to query data for a month. The size of a month's Excel data is about 1GB. Is there a better solution? Such as adding index queries? **Or any other good ideas**? Thank you

**Comment by 4upz** [comment] 2023-07-20 14:14
@365fed Awesome, glad that the MongoDB solution was able to improve things for you! 

Are you finding that it takes 2-minutes to query data that is already saved to MongoDB? Or is this saved data in combination with newly queried data? 

Also, are you seeing this load time when using the UI as well? Depending on the data size, the UI may still take a minute to load due to setting up all of the filters and graphs. However, we're looking into improving this

**Comment by 365fed** [comment] 2023-08-01 07:44
@4upz I use cli to generate historical data，and the data is very big
Here is my run script: 
`yarn start-cli --startDate 2023-03-01 --endDate 2023-03-02`
Here is the translation of the error message:
```<--- Last few GCs --->
[2268:0x140008000]   239289 ms: Mark-sweep 2018.1 (2082.1) -> 2002.6 (2082.6) MB, 716.0 / 0.0 ms  (average mu = 0.187, current mu = 0.083) allocation failure scavenge might not succeed
[2268:0x140008000]   240095 ms: Mark-sweep 2018.5 (2082.6) -> 2003.0 (2083.1) MB, 705.0 / 0.0 ms  (average mu = 0.159, current mu = 0.126) allocation failure scavenge might not succeed

<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100ef9c84 node::Abort() [/usr/local/bin/node]
 2: 0x100ef9e74 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/usr/local/bin/node]
 3: 0x10103e840 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10103e800 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1011c1d1c v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x1011c532c v8::internal::Heap::CollectSharedGarbage(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 7: 0x1011c24e4 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x1011bfe0c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1011cbb84 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]```

**Comment by 4upz** [comment] 2023-08-01 15:26
@365fed Thanks for sharing! Am I right to assume that you're seeing this after querying for one day of historical data? If so, we'd definitely have to take a closer look at that. It'd also be helpful to know what cloud providers you're using.

If you're doing larger date ranges, I'd recommend seeding your cache file using split requests for large ranges of historical data. See this[ section of our documentation](https://www.cloudcarbonfootprint.org/docs/performance-considerations#considerations-for-large-requests) for more information.

Sorry that you're running into these roadblocks. Let me know how I can support further based on the above questions/suggestions.

**Comment by 365fed** [comment] 2023-08-01 16:03
@4upz I am very happy to receive your reply！
I am currently querying 1 day data with start-cli,  i am using AWS cloud provider
Run `yarn start-cli --startDate 2023-03-01 --endDate 2023-03-02`,and it causing error about memory overflow
I am using AWS Athena query data from 2023-03-01  to 2023-03-02 , and the query result total number is 400,218,it just one days
But when i using `yarn start-cli --startDate 2023-03-01 --endDate 2023-03-02` it cannot work fine
Any idea or solutions ? thanks!
By the way, I want to use a scheduled task to fetch the latest data and cache it in the DB, pulling data from the previous day. I have a question about how many times per day I need to fetch the data to ensure its accuracy and timeliness. Also, when setting the carbon footprint, how do you compare data differences? Is it based on the date? I remember AWS generates billing data three times a day in the CUR report. How can I ensure the accuracy of the data? Thank you for your assistance.

**Comment by 4upz** [comment] 2023-08-01 16:37
@365fed No problem, happy to help!

That's definitely a lot of rows! One thing to note is that the endDate parameter is usually inclusive. So you are instead querying for 2 days consisting of both 2023-03-01 and 2023-03-02. I'd recommend changing the endDate to match 2023-03-01 so that you can query for a single day, thus reducing the amount of rows being calculated at one time. Let me know if that improves things.

For your scheduled task, you should be fine making only one request for the previous day. It is usually a good idea to maybe have it kick off once each morning in which it calculates estimates for the previous day. Although the CUR updates 3 times a day, the billing data for that day should be complete after that final update. Granted that there aren't any amendments to that date's billing data during a later date (which doesn't happen often), the data should be accurate enough

**Comment by 365fed** [comment] 2023-08-18 15:58
@4upz "Hello, I have encountered an urgent problem. I have successfully loaded data for the past year and generated it in estimates.cache.day.json. However, the issue is that I have set up a scheduled task to fetch the latest data. The task uses the carbon footprint API to retrieve the estimates data for the previous day at 12:00 PM every day. But I noticed that the data being inserted into the JSON file has formatting errors, resulting in an error in the backend API server. The error message is: 

`[1] 2023-08-18T15:35:45.909Z [App] info: Finished AWS Estimations 
[1] 2023-08-18T15:35:45.913Z [Cache] info: Setting new estimates to cache... 
[1] 2023-08-18T15:36:23.531Z [api] info: Footprint API request started. 
[1] 2023-08-18T15:36:23.541Z [Cache] info: Using local cache file... 
[1] SyntaxError: Unexpected token ] in JSON at position 0
[1]     at JSON.parse (<anonymous>)
[1]     at DelimitedStream.<anonymous> (/Users/jhh/fsdownload/carbon-0806/packages/app/src/common/helpers.ts:57:23)
[1]     at DelimitedStream.emit (events.js:400:28)
[1]     at DelimitedStream.emit (domain.js:475:12)
[1]     at addChunk (internal/streams/readable.js:293:12)
[1]     at readableAddChunk (internal/streams/readable.js:267:9)`

Here is json file as u view:
[preview image](https://images.weserv.nl/?url=https://article.biliimg.com/bfs/article/2cf0f85ea08b557629e4e1311268048fdeea2716.png)
Can you provide me with some solution ideas? Our company is currently using this project. Thank you!"

**Comment by 4upz** [comment] 2023-08-18 18:26
@365fed Sorry to hear that you're running into that issue. From the looks of it, it seems to be related to the bug reported in #1197. We have plans to look into this issue soon. As of right now, there's unfortunately no other solution for it at this moment outside of creating a script to manually remove that character or to delete the JSON file and refresh the cache with new estimates.

If you're company is using CCF and you are updating it with new estimates everyday, we _strongly encourage_ you to use the [MongoDB option](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching#json-file) for storing estimates instead. The JSON method is ideal for smaller installations or individuals looking for a temporary storage solution for their estimates, but does not scale very well and has plans to be deprecated with less support. For company-level usage, we recommend using a local or cloud MongoDB instance as it's more scalable and better at persisting larger estimates.
