### ISSUE TITLE
Graphs are not displayed on cloud usage graph on reports I can see the data but graphs displayed , When I save the graph has PNG file I can see the graphs 

### ISSUE THREAD

**Issue by manjunath-vs** [cloud-carbon-footprint/cloud-carbon-footprint#1069] opened 2023-03-07 13:32 UTC
I have deployed Cloud Carbon Foot using helm charts on Kubernetes Cluster and Exposed Cloud Carbon FootPrint Application on Ingress URL, We are able to access the application and we are able to see the Emission Breakdown and Cumulative Emissions but only issue we can see if unable to see Cloud Usage Graphs 

I can see the graphs if I save it has image on PNG format. But on the dashboard we are unable to see the graphs 

I have attached the screen shot for reference and also the PNG screen shot also for reference.

Suggest me how to fix the graph on application UI Dashboard 
-------------------------------------------------------------------------------------------------------------------
<img width="1560" alt="Screenshot 2023-03-07 at 6 54 56 PM" src="https://user-images.githubusercontent.com/28754838/223436696-ca7fdbcb-7755-4eb0-8445-41e5c47eabd1.png">
![lineChart(1)](https://user-images.githubusercontent.com/28754838/223436781-000b0fcf-b834-40d0-830d-13dc5bd22f78.png)
-------------------------------------------------------------------------------------------------------------------

**Comment by manjunath-vs** [comment] 2023-03-08 11:14
Hi Marlkiller,
Can you pls confirm if these fix are pushed to docker images.

Regards,

Manjunath VS

**Comment by 4upz** [comment] 2023-03-09 18:55
Hi @manjunath-vs thanks for opening this issue and trying out CCF! It seems your graph has duplicate dates which is most likely causing the line to be missing. This tells me that it must be an issue caused by a corrupted cache file -- which happens on rare occasions when using the local cache method. 

If you are indeed using the local [JSON Cache Method](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching/#json-file), then you may want to go inside of your container, clear your `estimates.[grouping].cache.json` file in your `packages/api` folder, and redeploy your cluster.  You can also change your client to ignore the cache by adding `REACT_APP_DISABLE_CACHE=true`. That being said, we recommend using the [MongoDB Storage Method](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching/#mongodb-storage) for caching and persisting your estimates as the JSON method will be deprecated soon.

Hope that helps! Let me know if that solves your issue. I see that @marlkiller may have added a potential fix to his fork. If he's willing to open a PR for it, we're happy to review it and possibly include it within our next scheduled (biweekly) release which is when the docker images are updated.

**Comment by manjunath-vs** [comment] 2023-03-12 13:30
Hi Arik Smith,

I have tried adding the attribute REACT_APP_DISABLE_CACHE=true on ConfigMap but I am still seeing the same issue, Any suggestions on this issue we do not want to use MongoDB storage Method as of now.

Regards,

Manjunath VS

**Comment by 4upz** [comment] 2023-03-23 15:26
@manjunath-vs Apologies for the late follow-up on this! Was the issue still persisting after adding the disable cache config to your `packages/client/.env` file? Just want to make sure it was added to the right place.

I'd recommend double-checking that first. You can verify that the config is recognized properly as you should see queries being made to the cloud provider (along with an "Ignoring Cache..." message) each time the page is loaded.  Alternatively, you can try disregarding the config, still using the cache, but deleting the corrupted cache file so that it is refreshed with the new request.

**Comment by bgauchon-reply** [comment] 2023-05-11 17:08
Hello I have same issue as EC2 install for new deployment (old AMI with ccf from 2022 march doesn't have this issue).
I can't disable cache as if I do so I encounter a proxy error timeout from app to api (I have like 2 years of data).
In fact I have to load the app, then encounter a 502 error (proxy timeout), then wait like 2 minutes for cache file being built ;
```
[1] 2023-05-11T16:50:58.245Z [CostAndUsageReports] info: Getting Athena Query Result Sets
[0] Proxy error: Could not proxy request /api/footprint?start=2022-05-11&end=2023-05-11&ignoreCache=false&groupBy=day&limit=50000&skip=0 from 127.0.0.1:3000 to http://localhost:4000.
[0] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
```
then I have the data but lines don't show up.
As far as I can see I don't have any duplicate dates in cache file
```
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {1..9} ; do echo "2023-04-0$i" ; grep "2023-04-0$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-01
1
2023-04-02
1
2023-04-03
1
2023-04-04
1
2023-04-05
1
2023-04-06
1
2023-04-07
1
2023-04-08
1
2023-04-09
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..9} ; do echo "2023-04-1$i" ; grep "2023-04-1$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-10
1
2023-04-11
1
2023-04-12
1
2023-04-13
1
2023-04-14
1
2023-04-15
1
2023-04-16
1
2023-04-17
1
2023-04-18
1
2023-04-19
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..9} ; do echo "2023-04-2$i" ; grep "2023-04-2$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-20
1
2023-04-21
1
2023-04-22
1
2023-04-23
1
2023-04-24
1
2023-04-25
1
2023-04-26
1
2023-04-27
1
2023-04-28
1
2023-04-29
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..1} ; do echo "2023-04-3$i" ; grep "2023-04-3$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-04-30
1
2023-04-31
0
[root@ip-10-0-0-147 cloud-carbon-footprint]# for i in {0..9} ; do echo "2023-05-0$i" ; grep "2023-05-0$i" packages/api/estimates.cache.day.json | wc -l ; done
2023-05-00
0
2023-05-01
1
2023-05-02
1
2023-05-03
1
2023-05-04
1
2023-05-05
1
2023-05-06
1
2023-05-07
1
2023-05-08
1
2023-05-09
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# grep "2023-05-10" packages/api/estimates.cache.day.json | wc -l
1
[root@ip-10-0-0-147 cloud-carbon-footprint]# grep "2023-05-11" packages/api/estimates.cache.day.json | wc -l
1
```
This only happen with newest code (graphs works fine on old code, but recommendations only show up for execution account which is fixed in newest code)
I will have a try at mongodb cache but I expect the timeout to happen any time I rebuild cache

**Comment by bgauchon-reply** [comment] 2023-05-25 18:52
I solved the issue on my side by having latest node LTS version ([Node v18.16.0 (LTS)](https://nodejs.org/en/blog/release/v18.16.0) instead of distribution by-default available.
Maybe someone could try on his side in order to confirm this

**Comment by darioackermann** [comment] 2023-10-27 21:36
Still an issue, at least on docker images. Regularly occurs after the caches are generated, even if only one request triggerd the cache-generation process.

**Comment by darioackermann** [comment] 2023-10-27 21:47
I can confirm that manually replacing the shipped `nodejs` (16) with version `18` works.

**Comment by 4upz** [comment] 2023-11-07 19:51
Hi all, apologies for the delay on this. Thanks for the insight @bgauchon-reply and @darioackermann. We've updated the dockerfiles of both the api and client to ship with Node 18. They will be released to dockerhub upon our next release. If you've cloned the repo, you can access them by using the `docker-compose.local.yml` file. 

@manjunath-vs If you still run into this issue even after this fix, feel free to let us know.

**Closed as completed by 4upz** 2023-11-07 19:51 UTC
